language: nix

cache:
  directories:
  - "/nix"

env:
  matrix:
    - COMPILER=ghc7103
    - COMPILER=ghc801
    - COMPILER=ghc821
    - COMPILER=ghcjsHEAD

script: nix-build --argstr compiler $COMPILER
