language: nix

cache:
  directories:
  - "/nix"

env:
  matrix:
    - COMPILER=ghc7103
    - COMPILER=ghc801
    - COMPILER=ghcjsHEAD

script: travis_wait nix-build -E 'with import <nixpkgs> { }; import ./default.nix { compiler=\"$COMPILER\"; }'
